version: 2.1
jobs:
  build-image:
    docker:
      - image: centos:7
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run: yum install -y sudo
      - run: ./scripts/setup_develop.sh
      - run: ./scripts/build_all.sh
      - store_artifacts:
          path: ./build/rpms/RPMS/x86_64/openrelay-0.9-9.x86_64.rpm
          destination: openrelay-0.9-9.x86_64.rpm
workflows:
  version: 2
  build:
    jobs:
      - build-image
