version: 2.1
jobs:
  build-image:
    machine: true
    docker:
      - image: docker.io/centos
    steps:
      - checkout
      - run: dnf install -y sudo
      - run: ./scripts/setup_develop.sh
      - run: ./scripts/build_all.sh
      - store_artifacts:
          path: ./build/rpms/RPMS/x86_64/openrelay-0.9-9.x86_64.rpm
          destination: openrelay-0.9-9.x86_64.rpm
workflows:
  version: 2
  build:
    jobs:
      - build-image
